### PR TITLE
Update to go 1.18 + update dependencies

### PR DESCRIPTION
**Pull request by Carbonique**
Hi there,

I stumbled upon your plugin last Friday, and you did a great job! I've been thinking of using it, but what held me back was that the plugin uses quite some old versions. I've made the following changes to update the plugin. None of them change the functionality

- update the plugin to Go 1.18. 
- update the dependencies (I implemented the latest version of the driver interface)
- use pointers for the volumedriver
- make some other minor changes to the code

How would you feel about merging the above?

### CODE REVIEW

**Comment by CWSpear** [comment]
I would feel good about merging! Good ol' Go deps...

Anyway, it's still marked as draft and you've been making some changes. Let me know when you're ready and we can merge.

We'll need new binaries, too.

**Comment by Carbonique** [comment]
Cool! I think the tests still need some work, as I've added some additional error handling which needs to be tested 

How would that work regarding binaries? Will you compile and upload them after the MR has been merged? Or would you need anything from me?

**Comment by CWSpear** [comment]
I can do it... hopefully. :)

**Comment by Carbonique** [comment]
I think that its for now. Integration tests + unit tests pass. I might open another PR in the (near) future to:

- add support for arm64 architecture 
- improve logging
- add support for a v2 plugin (if you're open to that)

But lets first see about this PR

**Comment by Carbonique** [comment]
Hi there,

Just a ping as I'm curious when you'll be able to check the PR @CWSpear

**Comment by CWSpear** [comment]
Sorry, was at a family reunion and I should have not even opened the email, cuz then when I got home, I completely forgot about it.

Anyway... why is Travis CI not cooperating? Trying to figure that out before I merge.

**Comment by CWSpear** [comment]
Superseded by https://github.com/MatchbookLab/local-persist/pull/88

**Pull request closed without merging**
